version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
  app:
    build: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - postgres